// src/components/Projects.tsx
import { styled } from "@linaria/react";

/** Data for all projects. */
const projects: {
	title: string,
	description: string
	url: string
	image?: string
}[] = [
	{
		"title": "Semantic Props",
		"description": "Expertly crafted CSS Custom Properties (variables) for creating consistent components in any design.",
		"url": "https://semantic-props.style/",
		"image": "/projects/semantic-props.png"
	},
	{
		"title": "Precolor",
		"description": "A collection of color manipulation tools written in Sass (SCSS).",
		"url": "https://github.com/JoshuaSand0val/Precolor"
	}
];

/** Listing of all affiliated projects. */
// Images must be of a viewport of 1200/800 CSS pixels.
export default function Projects() {
	const Grid = styled.div`
		display: flex;
		flex-flow: row nowrap;
		border-radius: var(--small);
		gap: var(--small);
		margin-block: var(--2x-large);
		scroll-snap-type: inline mandatory;
		overflow: auto;
		&:target {
			outline: var(--3x-small) solid var(--low-contrast-color);
			outline-offset: var(--3x-small);
		}
	`;

	const Project = styled.article`
		position: relative;
		z-index: 0;
		display: block;
		inline-size: min(100%, var(--medium-container));
		min-block-size: var(--small-container);
		border-radius: var(--small-radius);
		background-color: var(--gray-900);
		background-image: linear-gradient(to bottom right, var(--gray-850), var(--gray-900));
		color: var(--gray-50);
		text-shadow: var(--lightest-text-shadow);
		scroll-snap-align: center;
		overflow: hidden;
		flex: 0 0 auto;
		&:not(:has(img)) {
			background-color: var(--middleground-color);
			background-image: linear-gradient(var(--middleground-color), var(--foreground-color));
			color: var(--high-contrast-color);
		}
	`;

	const Portal = styled.img`
		display: block;
		inline-size: 100%;
		object-fit: cover;
		object-position: top center;
		mask-image: linear-gradient(transparent, black 25%, transparent);
		mask-type: alpha;
		overflow: hidden;
	`;

	const Description = styled.p`
		position: absolute;
		z-index: calc(var(--z-absolute) + 1);
		bottom: 0;
		display: block;
		font-size: var(--medium);
		font-style: italic;
		font-weight: var(--light-weight);
		line-height: var(--short-line);
		padding: var(--medium);
		padding-inline-end: var(--large);
		margin: 0;
	`;

	const Title = styled.span`
		display: block;
		font-style: normal;
		font-family: var(--display-family);
		font-size: var(--large);
		font-weight: var(--bold-weight);
		margin-block-end: var(--4x-small);
	`;

	const Link = styled.a`
		position: absolute;
		inset: 0;
		z-index: var(--z-absolute);
		display: flex;
		flex-flow: row nowrap;
		justify-content: end;
		align-items: start;
		font-size: var(--3x-large);
		line-height: 1;
		color: inherit;
		cursor: pointer;
		text-decoration: none;
		flex: 0 0 auto;
		padding: var(--medium);
		outline-offset: calc(-1 * var(--3x-small));
		transition: opacity var(--fast-time) var(--ease-in);
		&:hover, &:focus {
			opacity: var(--highest-opacity);
		}
		&:active {
			opacity: var(--higher-opacity);
			transition-duration: 0ms;
		}
	`;

	return (
		<Grid id="projects">
			{projects.map(({ title, image, description, url }, index) => (
				<Project key={index}>
					{typeof image === "string" && (
						<Portal src={image} loading="lazy" alt="" />
					)}
					<Description>
						<Title>{title}</Title>
						{description}
					</Description>
					<Link href={url}>
						<i className="bi bi-box-arrow-up-right" aria-label="Learn More"></i>
					</Link>
				</Project>
			))}
		</Grid>
	);
}

// src/routes/projects/+page.svelte
<script>
	import "bootstrap-icons/font/bootstrap-icons.min.css";
	import projects from "./projects.json";
	import Meta from "$lib/Meta.svelte";
</script>

<Meta title="Projects" description="The various projects undertaken by Jes." />

<!-- Project images must be of a viewport of 1200/800 CSS pixels. -->

<div class="container">
	<h1>My Projects</h1>
	<div class="grid">
		{#each projects as { title, image, description, url }}
		<div class="grid-item">
			<article class="project">
				<h2 class="project-title">{title}</h2>
				{#if typeof image === "string"}
				<a class="project-portal" href={url} target="_blank">
					<img src={image} loading="lazy" alt="" />
				</a>
				{/if}
				<p class="project-description">{description}</p>
				<span class="project-link">
					<a href={url} target="_blank">
						Learn More <i class="bi bi-chevron-right"></i>
					</a>
				</span>
			</article>
		</div>
		{/each}
	</div>
</div>

<style>
	h1 {
		margin: 0;
	}

	.grid {
		display: block;
		column-count: 4;
		column-width: var(--2xs-container);
		column-gap: var(--sm-size);
		column-fill: balance;
		margin: var(--md-size) 0;
	}

	.grid-item {
		display: block;
		break-inside: avoid;
		padding-bottom: var(--sm-size);
		&:last-child {
			padding-bottom: 0;
		}
	}

	.project {
		display: flex;
		flex-flow: column nowrap;
		justify-content: flex-start;
		border-radius: var(--3xs-size);
		border: 1px dashed var(--neutral-100-600);
		background-color: var(--neutral-50-800);
		box-shadow: 0 4px 16px -8px var(--theme-color-300);
		padding: var(--sm-size) 0 var(--xs-size);
		gap: var(--xs-size) 0;
		filter: var(--light-shadow);
	}

	.project-title,
	.project-portal,
	.project-description,
	.project-link {
		display: block;
		margin: 0 var(--sm-size);
	}

	.project-title {
		font-size: var(--xl-font);
	}

	.project-portal {
		position: relative;
		z-index: var(--relative-index);
		aspect-ratio: 3 / 2;
		width: 100%;
		border-radius: inherit;
		margin: 0;
		transition: all var(--fast-time) ease-out;
		overflow: hidden;
		&:hover, &:focus,
		.project:has(a[href]:is(:hover, :focus)) & {
			background-color: inherit;
			filter: var(--medium-shadow);
			transform: scale(1.05);
		}
		&, &:active,
		.project:has(a[href]:active) & {
			transition-duration: var(--swift-time);
			transform: scale(1.02);
		}
		img {
			display: block;
			width: 100%;
			height: 100%;
			object-fit: cover;
			object-position: top center;
		}
	}

	.project-description {
		margin-top: auto;
	}

	.project-link {
		text-align: right;
		border-top: inherit;
		padding-top: inherit;
	}
</style>
